name: GS test
favicon: null
layout_spectrum: 0.16446714708581567
typography_spectrum: 0.2838771026581526
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.2848147845361382
  lightness: 0.3263616762124002
  saturation: 0.563977065961808
  rhythmicContrast: 0.4205814665183425
purpose: []
